### ISSUE TITLE
Doesn't annotate IIFE

### ISSUE THREAD

**Issue by cawabunga** [morlay/babel-plugin-pure-calls-annotation#39]
I found that either documentation isn't correct or it's a bug, because immediately invoked functions (IIFE) aren't being processed. 

script.js:
```javascript
export const call = (s) => {
  return "call" + s
}

export const stringA = call("a")
export const stringB = (() => call("b"))()
```
Run in console (babel v7):
```
$ npx babel --plugins pure-calls-annotation script.js

export const call = s => {
  return "call" + s;
};
export const stringA = /*#__PURE__*/call("a");
export const stringB = (() => call("b"))();

**Comment by morlay** [comment]
@cawabunga I upgrade to babel 7.15

haven't seen this issue.

test case here: https://github.com/morlay/babel-plugin-pure-calls-annotation/blob/master/src/__tests__/index.spec.ts#L75-L77

**Notice**: the plugin will not process body in IIFE, which will be a hack to let people write logic with side effects.

**Comment by cawabunga** [comment]
I've written such test case:
```javascript
{
  title: "Annotated #__PURE__ for defined add(0, 1) called in IIFE",
  src: `const add = (x, y) => x + y; export const one = (() => add(0, 1))();`,
  dest: `const add = (x, y) => x + y; export const one = /*#__PURE__*/(() => add(0, 1))();`,
},
```
I was expecting that it would pass, but it wouldn't. Do you have any suggestions?

**Comment by morlay** [comment]
@cawabunga 0.4.2 should fix this.

here a special case to ignore annotating `#__PURE__`, old codes will wrong check for your case
```js
const a = setInterval(() => {
    console.log(a)
}, 1000)
```

Where `#__PURE__` here, tools like `uglify` will remove all statement.

**Comment by cawabunga** [comment]
Can confirm that everything is working. @morlay thank you!
